version: '3.8'
services: 
  # go-api: 
    # image: golang 
    # hostname: go-api
    # ports:
      # - ${API_PORT}:${API_PORT}
    # container_name: go-api
    # working_dir: /usr/src/app
    # build: .
    # volumes: 
      # - ./:/usr/src/app
    # networks:
      # - go-api
    # tty: true 

  gym-db:
    env_file:
      - ./.env
    container_name: gym-db
    hostname: gym-db
    ports:
      - ${MYSQL_PORT}:${MYSQL_PORT}
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USERNAME: ${MYSQL_USERNAME}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    build: 
      context: ./app/database/
      dockerfile: Dockerfile
    volumes:
      - ./app/database/:/docker-entrypoint-initdb.d
    restart: unless-stopped
    networks:
      - go-api

networks: 
  go-api:
    driver: bridge